name: App Deploy in KinD

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag notes:v1
    - name: Save Docker image as tarball
      run: docker save -o /tmp/notes.tar notes:v1
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: /tmp/notes.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image tarball artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: /tmp
      - name: Load Docker image from tarball
        run: |
          docker load --input /tmp/notes.tar
          docker image ls -a   
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1 
      - name: Run KinD commands
        run: |
          kind version
          kind get clusters
          kind load docker-image notes:v1 --name chart-testing
          helm version
          helm install notes helm-charts/notes/
          sleep 30
          kubectl get all
          sleep 60
          kubectl get all